import type { ArchivePhoto } from "@/lib/portfolio-archive";

export const PHOTO_STYLES = [
  "Aerial / Drone",
  "Architecture",
  "Street / Urban",
  "Landscape / Nature",
  "Portrait / Lifestyle",
  "Travel / Documentary",
] as const;

export type PhotographyStyle = (typeof PHOTO_STYLES)[number];
export type PhotographySeriesSlug = string;

export type PhotographySeriesDefinition = {
  slug: PhotographySeriesSlug;
  title: string;
  kicker: string;
  location: string;
  description: string;
  sortDate: string;
  coverId?: string;
  public: boolean;
};

export type CataloguePhoto = Pick<ArchivePhoto, "id" | "src" | "width" | "height"> & {
  title: string;
  seriesSlug: PhotographySeriesSlug;
  seriesTitle: string;
  styles: PhotographyStyle[];
};

// Projects are destination-first. A small legacy-classification pass is kept only so that
// user-reviewed photo numbers still refer to the exact pre-merge project sequence.
export const PHOTOGRAPHY_SERIES: PhotographySeriesDefinition[] = [
  {
    slug: "south-florida-2026-06-20",
    title: "South Florida & Florida Keys · 20–25 June 2026",
    kicker: "20–25 Jun 2026",
    location: "South Florida & Florida Keys, USA",
    description: "A South Florida sequence moving from Miami and the Atlantic coast into the Florida Keys, combining ground-level travel work with aerial photography.",
    coverId: "1iWALyhGcc9kTYzVj4DPUWwnhQwIvwapU",
    sortDate: "2026-06-25",
    public: true,
  },
  {
    slug: "new-england-2026-06-15",
    title: "New England · 15–17 June 2026",
    kicker: "15–17 Jun 2026",
    location: "Rhode Island & Massachusetts, USA",
    description: "A coastal New England travel sequence spanning Newport, Rhode Island and Cape Cod, Massachusetts.",
    coverId: "1fLYoVGasJLmqujPlQuM_pyEIBKYsy48a",
    sortDate: "2026-06-17",
    public: true,
  },
  {
    slug: "new-york-2026-06-10",
    title: "New York · 10–13 June 2026",
    kicker: "10–13 Jun 2026",
    location: "New York City, USA",
    description: "One New York trip spanning several shooting days, from Central Park and Manhattan streets to the wider city skyline.",
    coverId: "1IusmytpZjQWH7WUnS_KPk79qH0Q8qIpu",
    sortDate: "2026-06-13",
    public: true,
  },
  {
    slug: "buckinghamshire-2026-04-29",
    title: "Buckinghamshire · February–April 2026",
    kicker: "21 Feb & 29 Apr 2026",
    location: "Buckinghamshire, England",
    description: "Two Buckinghamshire aerial sessions from the same body of work, photographed on 21 February and 29 April 2026 and presented together rather than as duplicate local projects.",
    coverId: "1ZIyG800JyxP6NvCINK_qXUpExjCVzfVj",
    sortDate: "2026-04-29",
    public: true,
  },
  {
    slug: "landscape-2026-04-18",
    title: "Uffington · 18 April 2026",
    kicker: "18 Apr 2026",
    location: "Uffington, Oxfordshire",
    description: "A spring landscape and aerial study around Uffington and the White Horse landscape in Oxfordshire.",
    coverId: "1CsGLtzMytXXjF2p1RhdXVEfRMhAr2yzy",
    sortDate: "2026-04-18",
    public: true,
  },
  {
    slug: "aerial-2026-03-04",
    title: "Obergurgl · 3–6 March 2026",
    kicker: "3–6 Mar 2026",
    location: "Obergurgl, Tyrol, Austria",
    description: "A high-alpine Tyrol sequence around Obergurgl, bringing together phone and drone photography from the same mountain trip.",
    coverId: "1Nj0do07_34xgSytD4CTeIlHNd2C2sFDM",
    sortDate: "2026-03-06",
    public: true,
  },
  {
    slug: "london-2026-02-25",
    title: "London · 25 February 2026",
    kicker: "25 Feb 2026",
    location: "London, England",
    description: "A Thames and City sequence photographed as one distinct London shoot.",
    coverId: "1YF4F-7PFa-z0hXjRHCKI7X0lzLoiYUX3",
    sortDate: "2026-02-25",
    public: true,
  },
  {
    slug: "buckinghamshire-2026-02-07",
    title: "HS2 · 2024–26",
    kicker: "Sep 2024–Feb 2026",
    location: "Buckinghamshire, England",
    description: "An aerial study of the HS2 landscape and infrastructure as it changes over time, bringing together the relevant September 2024, August 2025 and February 2026 photographs.",
    coverId: "15dDs-ptn3gXKL2-L0h1ycJqtc5Y8RK6V",
    sortDate: "2026-02-07",
    public: true,
  },
  {
    slug: "thailand-2025-12-25",
    title: "Thailand · 16–25 December 2025",
    kicker: "16–25 Dec 2025",
    location: "Thailand",
    description: "A December Thailand trip combining tropical travel photography with aerial work, including a GPS-confirmed drone sequence from Koh Mak.",
    coverId: "1Ut3K_751y7fuMBJ68nwJ-KmzoSRDi2X9",
    sortDate: "2025-12-25",
    public: true,
  },
  {
    slug: "athens-2025-11-14",
    title: "Athens · 14–15 November 2025",
    kicker: "14–15 Nov 2025",
    location: "Athens, Greece",
    description: "An Athens city study spanning two days, centred on the Acropolis and the surrounding urban fabric with both ground and aerial work.",
    coverId: "1CUijocKG4rV6mjWpQJj8EtI02hYbUqnb",
    sortDate: "2025-11-15",
    public: true,
  },
  {
    slug: "transformation-series",
    title: "Transformation Series · October–November 2025",
    kicker: "8 Oct–6 Nov 2025",
    location: "Buckinghamshire, England",
    description: "A repeated aerial study of the same Buckinghamshire landscape through October and early November, including the newly recovered 8, 15, 21 and 25 October and 6 November DJI export sequences.",
    coverId: "1imXc4whdAAR8-9P8VPtGOaHBsAgEbBIl",
    sortDate: "2025-11-06",
    public: true,
  },
  {
    slug: "sicily-2025-08-28",
    title: "Sicily · 28 August–3 September 2025",
    kicker: "28 Aug–3 Sep 2025",
    location: "Sicily, Italy",
    description: "One Sicily journey spanning coast, hill towns, Baroque architecture and street detail, with the ground and drone work kept together as a single trip.",
    coverId: "1ScrcYlxrEZj5KQX2PN53rv78u_33Qmao",
    sortDate: "2025-09-03",
    public: true,
  },
  {
    slug: "mediterranean-2025-07-15",
    title: "Mediterranean · 15–20 July 2025",
    kicker: "15–20 Jul 2025",
    location: "Mediterranean",
    description: "One Mediterranean coastal journey combining evening, marina and aerial sequences from the same trip while keeping the exact locality deliberately broad.",
    coverId: "1KrYjwZrHhigVC3ilcNdpkRiroKlihWpN",
    sortDate: "2025-07-20",
    public: true,
  },
  {
    slug: "coast-2025-07-01",
    title: "South Devon · 30 June–3 July 2025",
    kicker: "30 Jun–3 Jul 2025",
    location: "South Devon, England",
    description: "A South Devon coastal body of work spanning several days, combining the Sony sequence with GPS-confirmed aerial photographs from the same trip.",
    coverId: "1IDjDb8Ro4uLQd4TxeooQO2YqIcCl9ugC",
    sortDate: "2025-07-03",
    public: true,
  },
  {
    slug: "austria-2025-05-30",
    title: "Austria · 30 May 2025",
    kicker: "30 May 2025",
    location: "Austria",
    description: "An Austrian travel sequence of architecture, landscape and street detail, with the ground and drone work from the same shoot kept together.",
    coverId: "1IK3fj_yf2q7ObrbNe6_ZUgt_tZf8pUM0",
    sortDate: "2025-05-30",
    public: true,
  },
  {
    slug: "paris-2025-04-11",
    title: "Paris · 11–14 April 2025",
    kicker: "11–14 Apr 2025",
    location: "Paris, France",
    description: "One Paris trip spanning several shooting days, combining street, architecture and GPS-confirmed aerial work around the city.",
    coverId: "1Gso9_NEVE78jrRZ-1KTPCKBM8n9xqyAJ",
    sortDate: "2025-04-14",
    public: true,
  },
  {
    slug: "glasgow-2025-03-23",
    title: "Glasgow · March 2025",
    kicker: "Mar 2025",
    location: "Glasgow, Scotland",
    description: "A Glasgow street and architecture study, including the photograph previously mis-filed in the 16 March London sequence.",
    coverId: "13b4VawuFrjR_Rhjube5YPKFogdkkwSsB",
    sortDate: "2025-03-23",
    public: true,
  },
  {
    slug: "architecture-2025-02-22",
    title: "London in Monochrome · February–May 2025",
    kicker: "22 Feb–3 May 2025",
    location: "London, England",
    description: "Black-and-white studies of London architecture brought together as one coherent body of work instead of three near-duplicate dated projects.",
    coverId: "1xfCT3SqAcS99bpTu1tFGa3Z377fNdllP",
    sortDate: "2025-05-03",
    public: true,
  },
  {
    slug: "tyrol-2025-02-16",
    title: "Zürich & Tyrol · 14–18 February 2025",
    kicker: "14–18 Feb 2025",
    location: "Switzerland & Austria",
    description: "One Alpine journey beginning in Zürich and continuing into Tyrol, combining the city, mountain and aerial photography from the same trip.",
    coverId: "10HqNSdmEWcN6U0JvNfoaY6DHsDMAOymK",
    sortDate: "2025-02-18",
    public: true,
  },
  {
    slug: "still-life-2025-01-06",
    title: "Still Life · 6 January 2025",
    kicker: "6 Jan 2025",
    location: "Studio",
    description: "A studio still-life and texture sequence kept out of the travel catalogue.",
    coverId: "1KbNLtotWQfuf0gja27iQCtewnr5Ei6oQ",
    sortDate: "2025-01-06",
    public: true,
  },
  {
    slug: "aerial-2024-09-19",
    title: "Buckinghamshire · 19 September 2024",
    kicker: "19 Sep 2024",
    location: "Buckinghamshire, England",
    description: "A GPS-confirmed Buckinghamshire aerial session; its third photograph now sits with the HS2 progression series where it belongs.",
    coverId: "1KbaJm36IAigDCqf9necpF9wPbTrAUO69",
    sortDate: "2024-09-19",
    public: true,
  },
  {
    slug: "london-2024-08-04",
    title: "London · 4 August 2024",
    kicker: "4 Aug 2024",
    location: "London, England",
    description: "A London architecture sequence including Battersea Power Station.",
    coverId: "1Mz6Na0cnuxIjljmApw_Tz6y0cEihiDl6",
    sortDate: "2024-08-04",
    public: true,
  },
  {
    slug: "summer-2024-07-29",
    title: "Summer Study · 29 July 2024",
    kicker: "29 Jul 2024",
    location: "United Kingdom",
    description: "A summer park and fairground sequence kept as a separate dated shoot while the exact location remains unconfirmed.",
    coverId: "1As-YU0qZx4QTTueYwHQL--LWuBMJ3mU0",
    sortDate: "2024-07-29",
    public: true,
  },
  {
    slug: "strasbourg-2024-06-21",
    title: "Strasbourg · 21 June 2024",
    kicker: "21 Jun 2024",
    location: "Strasbourg, France",
    description: "Canals, timbered architecture and street detail from Strasbourg.",
    coverId: "1TRTlQ-8eN5BKF_lLrODRo5FqiaRdFmvH",
    sortDate: "2024-06-21",
    public: true,
  },
  {
    slug: "edinburgh-2022-08-19",
    title: "Edinburgh · 19 August 2022",
    kicker: "19 Aug 2022",
    location: "Edinburgh, Scotland",
    description: "An aerial Edinburgh sequence kept separate from the wider Scottish journey, with the Barcelona outlier removed.",
    coverId: "1HYaDRBblLLYsbnn_i7rj5VBMDxAUHp8w",
    sortDate: "2022-08-19",
    public: true,
  },
  {
    slug: "flamborough-2022-08-19",
    title: "Flamborough · 19 August 2022",
    kicker: "19 Aug 2022",
    location: "East Yorkshire, England",
    description: "A separate evening aerial session on the same date, with GPS placing the sequence around the Flamborough coast.",
    coverId: "1wCawwinX-Qkrxcn6eIGLh4jyuHJIW1Ap",
    sortDate: "2022-08-19",
    public: true,
  },
  {
    slug: "barcelona-aerial",
    title: "Barcelona · Aerial Study",
    kicker: "Date to verify",
    location: "Barcelona, Spain",
    description: "Barcelona aerial photographs recovered from the Scottish Highlands and Edinburgh groups after the location mismatch was identified.",
    sortDate: "2022-08-18",
    public: true,
  },
  {
    slug: "highlands-2022-08",
    title: "Scottish Highlands · August 2022",
    kicker: "Aug 2022",
    location: "Scottish Highlands",
    description: "Highland aerial work from the wider journey, kept separate from Glenfinnan, Edinburgh and the photographs now correctly assigned to Barcelona.",
    sortDate: "2022-08-15",
    public: true,
  },
  {
    slug: "glenfinnan-2022-08-13",
    title: "Glenfinnan · 13 August 2022",
    kicker: "13 Aug 2022",
    location: "Glenfinnan, Scotland",
    description: "Drone studies around Glenfinnan and the viaduct, verified against original capture time and GPS.",
    coverId: "1brvBeAr_V3HreAuopD87U6K0hxffR63F",
    sortDate: "2022-08-13",
    public: true,
  },
  {
    slug: "thailand-2021-12",
    title: "Thailand · December 2021",
    kicker: "Dec 2021",
    location: "Thailand",
    description: "Earlier tropical aerial photography reclassified by location instead of being left in a generic early archive.",
    coverId: "1_iKfJFpHW1cVnxmwK2jRJjcvmYa7fJAx",
    sortDate: "2021-12-24",
    public: true,
  },
  {
    slug: "preca-italy",
    title: "Preca, Italy",
    kicker: "Early aerial study",
    location: "Preca, Italy",
    description: "An older aerial sequence grouped by its verified location rather than being presented as part of a miscellaneous early archive.",
    sortDate: "2021-12-15",
    public: true,
  },
  {
    slug: "open-archive",
    title: "Open Archive",
    kicker: "Location pending",
    location: "UK & international",
    description: "Work that remains available through the full archive filter until its original capture location can be verified confidently.",
    sortDate: "1900-01-01",
    public: false,
  },
].sort((a, b) => b.sortDate.localeCompare(a.sortDate));
